services:
  client:
    build:
      context: ../MelodiesWeb_FrontEnd
    ports:
      - "3000:3000"
    volumes:
      - ../MelodiesWeb_FrontEnd:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Use polling for hot-reload in certain environments

  server:
    build:
      context: ../MelodiesWeb_BackEnd
    ports:
      - "3001:3001"
    volumes:
      - ../MelodiesWeb_BackEnd:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Use polling for hot-reload in certain environments
    depends_on:
      - postgres
      - pgadmin
      - redis

  postgres:
    image: postgres:16-alpine
    volumes:
      - ./src/database/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./src/database/pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7.2-alpine
    volumes:
      - ./src/database/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
